import dev.klbt.ageds.core.WavHeaderObservation
import dev.klbt.ageds.core.WavHeaderProbe
import java.util.Base64
import java.security.MessageDigest
import kotlinx.serialization.json.*

/** Receives exactly the harness-generated bytes, never interprets fixture recipes. */
fun main() {
    val json = Json { encodeDefaults = true }
    System.`in`.bufferedReader(Charsets.UTF_8).useLines { lines ->
        lines.forEach { line ->
            val request = json.parseToJsonElement(line).jsonObject
            val bytes = Base64.getDecoder().decode(request.getValue("prefix_base64").jsonPrimitive.content)
            fun digest(value: ByteArray) = MessageDigest.getInstance("SHA-256").digest(value).joinToString("") { "%02x".format(it.toInt() and 255) }
            val suppliedHash = digest(bytes)
            val size = request.getValue("provider_size_bytes").let { if (it is JsonNull) null else it.jsonPrimitive.long }
            val observation = WavHeaderProbe.probe(bytes, size, request.getValue("end_of_input").jsonPrimitive.boolean)
            val output = buildJsonObject {
                put("id", request.getValue("id"))
                put("supplied_sha256", suppliedHash)
                put("input_unchanged", digest(bytes) == suppliedHash)
                put("observation", json.encodeToJsonElement(WavHeaderObservation.serializer(), observation))
            }
            println(json.encodeToString(JsonObject.serializer(), output))
        }
    }
}
