"""Worker/adapter verified-stream contract; generated bytes and fake ASR only."""
from dataclasses import replace
import hashlib
import io
import json
from pathlib import Path
import sys
import tempfile
from types import SimpleNamespace
import unittest
from unittest.mock import patch

from server.app import db, jobs, transcription, worker
from server.app.verified_reader import VerifiedReader
from server.app.verified_media import MediaIntegrityError, MediaUnavailable


class VerifiedWorkerTests(unittest.TestCase):
    def setUp(self):
        temp = tempfile.TemporaryDirectory()
        self.addCleanup(temp.cleanup)
        self.root = Path(temp.name)
        self.store = self.root / 'store'
        self.store.mkdir()
        settings = replace(db.settings, db_path=self.root / 'db.sqlite', store_dir=self.store)
        for module in (db, worker):
            patcher = patch.object(module, 'settings', settings)
            patcher.start()
            self.addCleanup(patcher.stop)
        db.init_db()
        self.original = b'synthetic decoder input\x00\xff'
        self.audio = self.store / 'input.wav'
        self.audio.write_bytes(self.original)
        with db.session() as conn:
            self.aid = conn.execute('INSERT INTO artifacts(original_name,mime_type,stored_path,sha256,size_bytes) VALUES (?,?,?,?,?)',
                ('input.wav', 'audio/wav', str(self.audio), hashlib.sha256(self.original).hexdigest(), len(self.original))).lastrowid
        self.job = None

    def run_adapter(self, adapter):
        transcription.queue_transcription(self.aid)
        self.job = jobs.claim_job()
        return worker.process_job(self.job, adapter)

    def rows(self, table):
        with db.session() as conn:
            return [dict(row) for row in conn.execute(f'SELECT * FROM {table} ORDER BY id')]

    def adapter(self, action):
        class Adapter:
            def describe(self):
                return {'tool': 'synthetic', 'model': 'fake', 'provider': 'test'}
            def transcribe(self, source):
                action(source)
                return worker.TranscriptionResult(' raw ASR ', 'en', [{'start': 0, 'end': 1, 'text': ' raw ASR '}],
                    {'input_mode': 'untrusted override', 'input_verification': {'final_same_descriptor': 'untrusted'}})
        return Adapter()

    def test_worker_passes_verified_stream_keeps_open_then_closes_and_records_checks(self):
        seen = []
        def decode(source):
            seen.append(source)
            self.assertIsInstance(source, VerifiedReader)
            self.assertFalse(source.closed)
            self.assertEqual(self.original[:5], source.read(5))
            source.seek(-2, io.SEEK_END)
            self.assertEqual(self.original[-2:], source.read())
        self.run_adapter(self.adapter(decode))
        self.assertTrue(seen[0].closed)
        metadata = json.loads(self.rows('derived_text')[0]['metadata_json'])
        provenance = json.loads(self.rows('processing_runs')[0]['provenance_json'])
        for data in (metadata, provenance):
            self.assertEqual('verified_seekable_filelike', data['input_mode'])
            self.assertEqual('passed', data['input_verification']['initial_full_sha256'])
            self.assertEqual('passed', data['input_verification']['final_same_descriptor'])
            self.assertEqual('not_measured', data['input_verification']['decoder_read_coverage'])
        self.assertEqual('done', self.rows('jobs')[0]['status'])

    def test_path_replacement_cannot_redirect_decoder_after_open(self):
        displaced = self.store / 'retained-original.wav'
        def decode(source):
            self.audio.rename(displaced)
            self.audio.write_bytes(b'X' * len(self.original))
            self.assertEqual(self.original, source.read())
        self.run_adapter(self.adapter(decode))
        self.assertEqual('done', self.rows('jobs')[0]['status'])
        self.assertEqual(self.original, displaced.read_bytes())

    def test_in_place_mutation_is_rejected_before_decoder_receives_bytes_even_if_restored(self):
        decoded = []
        captured = []
        def decode(source):
            captured.append(source)
            self.audio.write_bytes(b'X' * len(self.original))
            try:
                decoded.append(source.read())
            finally:
                self.audio.write_bytes(self.original)
        with self.assertRaises(MediaIntegrityError):
            self.run_adapter(self.adapter(decode))
        self.assertEqual([], decoded)
        self.assertEqual([], self.rows('derived_text'))
        self.assertTrue(captured[0].closed)
        self.assertEqual('failed', self.rows('processing_runs')[0]['status'])

    def test_final_descriptor_check_refuses_changed_unread_bytes(self):
        def decode(source):
            self.assertEqual(self.original[:1], source.read(1))
            with self.audio.open('r+b') as writer:
                writer.seek(-1, io.SEEK_END)
                writer.write(b'Z')
        with self.assertRaises(MediaIntegrityError):
            self.run_adapter(self.adapter(decode))
        self.assertEqual([], self.rows('derived_text'))
        provenance = json.loads(self.rows('processing_runs')[0]['provenance_json'])
        self.assertEqual('failed', provenance['input_verification']['final_same_descriptor'])

    def test_missing_recorded_size_refused_before_adapter_not_backfilled(self):
        with db.session() as conn:
            conn.execute('UPDATE artifacts SET size_bytes=NULL WHERE id=?', (self.aid,))
        called = []
        with self.assertRaises(MediaIntegrityError):
            self.run_adapter(self.adapter(lambda source: called.append(source)))
        self.assertEqual([], called)
        self.assertEqual([], self.rows('derived_text'))
        self.assertIsNone(self.rows('artifacts')[0]['size_bytes'])

    def test_outside_store_path_refused(self):
        outside = self.root / 'outside.wav'
        outside.write_bytes(self.original)
        with db.session() as conn:
            conn.execute('UPDATE artifacts SET stored_path=? WHERE id=?', (str(outside), self.aid))
        called = []
        with self.assertRaises(MediaUnavailable):
            self.run_adapter(self.adapter(lambda source: called.append(source)))
        self.assertEqual([], called)
        self.assertEqual([], self.rows('derived_text'))

    def test_adapter_failure_closes_stream_and_cannot_publish(self):
        seen = []
        def decode(source):
            seen.append(source)
            raise RuntimeError('synthetic decoder failure')
        with self.assertRaisesRegex(RuntimeError, 'synthetic decoder failure'):
            self.run_adapter(self.adapter(decode))
        self.assertTrue(seen[0].closed)
        self.assertEqual([], self.rows('derived_text'))
        self.assertEqual('failed', self.rows('jobs')[0]['status'])

    def test_faster_whisper_gets_same_object_and_exhausts_lazy_segments_inside_lifetime(self):
        received = []
        original = self.original
        class FakeModel:
            def __init__(self, *args, **kwargs): pass
            def transcribe(self, source, **kwargs):
                received.append(source)
                def segments():
                    self_source = received[0]
                    assert not self_source.closed
                    assert self_source.read() == original
                    yield SimpleNamespace(start=0.0, end=1.0, text=' raw ASR ', words=[])
                return segments(), SimpleNamespace(language='en')
        with patch.dict(sys.modules, {'faster_whisper': SimpleNamespace(WhisperModel=FakeModel)}):
            self.run_adapter(worker.FasterWhisperAdapter())
        self.assertIsInstance(received[0], VerifiedReader)
        self.assertTrue(received[0].closed)
        self.assertEqual('raw ASR', self.rows('derived_text')[0]['text'])
        self.assertEqual(' raw ASR ', json.loads(self.rows('derived_text')[0]['segments_json'])[0]['text'])


if __name__ == '__main__':
    unittest.main()
