"""Verified media owner tests use generated bytes only."""
import asyncio
import hashlib
import os
from pathlib import Path
import tempfile
import unittest
from unittest.mock import patch

from server.app import verified_media as vm


class VerifiedMediaTests(unittest.TestCase):
    def setUp(self):
        temp = tempfile.TemporaryDirectory()
        self.addCleanup(temp.cleanup)
        self.root = Path(temp.name)
        self.path = self.root / 'media.bin'
        self.data = bytes(range(256)) * 2049
        self.path.write_bytes(self.data)
        self.digest = hashlib.sha256(self.data).hexdigest()

    def response(self, **kwargs):
        return vm.verified_media_response(self.path, self.digest, len(self.data), store_root=self.root, **kwargs)

    def call(self, response, send=None):
        messages = []
        async def collect(message):
            messages.append(message)
        async def receive():
            await asyncio.Future()
        asyncio.run(response({'type': 'http', 'asgi': {'spec_version': '2.4'}}, receive, send or collect))
        return messages

    def test_whole_and_ranges_have_exact_bytes_and_close(self):
        for raw, expected, status in ((None, self.data, 200), ('bytes=17-300', self.data[17:301], 206),
                                      ('bytes=-13', self.data[-13:], 206), ('bytes=500000-', self.data[500000:], 206)):
            with self.subTest(raw=raw):
                response = self.response(range_header=raw)
                messages = self.call(response)
                self.assertEqual(messages[0]['status'], status)
                self.assertEqual(b''.join(m.get('body', b'') for m in messages), expected)
                self.assertIsNone(response.media.fd)

    def test_rename_replacement_does_not_reopen_path(self):
        response = self.response()
        self.path.rename(self.root / 'original')
        self.path.write_bytes(b'x' * len(self.data))
        messages = self.call(response)
        self.assertEqual(b''.join(m.get('body', b'') for m in messages), self.data)

    def test_in_place_mutation_never_yields_altered_chunk(self):
        response = self.response()
        messages = []
        async def send(message):
            messages.append(message)
            if message['type'] == 'http.response.body':
                with self.path.open('r+b') as stream:
                    stream.seek(vm.CHUNK_SIZE)
                    stream.write(b'changed')
        with self.assertRaises(vm.MediaIntegrityError):
            self.call(response, send)
        self.assertEqual(b''.join(m.get('body', b'') for m in messages), self.data[:vm.CHUNK_SIZE])
        self.assertIsNone(response.media.fd)

    def test_range_verifies_entire_covering_chunk(self):
        response = self.response(range_header='bytes=10-19')
        with self.path.open('r+b') as stream:
            stream.seek(50)
            stream.write(b'changed')
        with self.assertRaises(vm.MediaIntegrityError):
            self.call(response)
        self.assertIsNone(response.media.fd)

    def test_initial_integrity_unknown_size_and_bounds(self):
        for digest, size in ((self.digest, None), (self.digest, True), ('bad', len(self.data)),
                             ('0' * 64, len(self.data)), (self.digest, len(self.data) - 1)):
            with self.subTest(size=size, digest=digest), self.assertRaises(vm.MediaIntegrityError):
                vm.verified_media_response(self.path, digest, size)
        with patch.object(vm, 'MAX_MEDIA_BYTES', 10), self.assertRaises(vm.MediaLimitError):
            self.response()

    def test_nonregular_symlinks_and_parent_symlinks_reject(self):
        self.path.unlink()
        os.mkfifo(self.path)
        with self.assertRaises(vm.MediaUnavailable):
            self.response()
        self.path.unlink()
        outside = self.root / 'outside'
        outside.write_bytes(self.data)
        self.path.symlink_to(outside)
        with self.assertRaises(vm.MediaUnavailable):
            self.response()
        folder = self.root / 'real'
        folder.mkdir()
        (folder / 'file').write_bytes(self.data)
        (self.root / 'linked').symlink_to(folder)
        with self.assertRaises(vm.MediaUnavailable):
            vm.verified_media_response(self.root / 'linked/file', self.digest, len(self.data), store_root=self.root)

    def test_head_if_range_and_invalid_ranges(self):
        head = self.response(head=True, range_header='bytes=1-2')
        self.assertEqual(head.status_code, 200)
        self.assertEqual(head.headers['content-length'], str(len(self.data)))
        self.assertEqual(head.body, b'')
        for raw in ('bytes=1-2,4-5', 'units=1-2', 'bytes=-0', 'bytes=9-1', 'bytes=99999999-', 'bytes='):
            with self.subTest(raw=raw):
                response = self.response(range_header=raw)
                self.assertEqual(response.status_code, 416)
                self.assertEqual(response.headers['content-range'], f'bytes */{len(self.data)}')
        response = self.response(range_header='bytes=1-2', if_range='"not-current"')
        self.assertEqual(response.status_code, 200)
        response.close()
        response = self.response(range_header='bytes=1-2', if_range='"sha256:' + self.digest + '"')
        self.assertEqual(response.status_code, 206)
        response.close()

    def test_embedded_nul_path_is_typed_unavailable_before_open(self):
        for path, root in ((str(self.path) + '\x00tail', self.root),
                           (self.path, str(self.root) + '\x00tail')):
            with self.subTest(path=path, root=root), patch.object(vm.os, 'open', side_effect=AssertionError('must not open invalid pathname')):
                with self.assertRaises(vm.MediaUnavailable):
                    vm.verified_media_response(path, self.digest, len(self.data), store_root=root)

    def test_failed_send_closes_and_header_controls_reject(self):
        response = self.response()
        async def send(_):
            raise RuntimeError('client failed')
        with self.assertRaises(RuntimeError):
            self.call(response, send)
        self.assertIsNone(response.media.fd)
        with self.assertRaises(vm.MediaIntegrityError):
            self.response(media_type='audio/wav\r\nInjected: yes')
        response = self.response(filename='name\r\nInjected: yes.wav')
        self.assertNotIn('\r', response.headers['content-disposition'])
        response.close()
