"""Pure bounded WAV declarations; generated byte fixtures only."""
import json
import math
import struct
import unittest

from server.app.wav_header import MAX_PREFIX_BYTES, probe_wav_header


def chunk(name, payload=b'', declared=None):
    return name + struct.pack('<I', len(payload) if declared is None else declared) + payload + (b'\0' if len(payload) % 2 else b'')


def fmt(code=1, channels=1, rate=8000, bits=16, byte_rate=None, extra=b''):
    align = channels * (bits // 8)
    return chunk(b'fmt ', struct.pack('<HHIIHH', code, channels, rate,
                                     rate * align if byte_rate is None else byte_rate, align, bits) + extra)


def riff(*chunks):
    body = b'WAVE' + b''.join(chunks)
    return b'RIFF' + struct.pack('<I', len(body)) + body


def prefix_only(size=16000):
    data = bytearray(riff(fmt(), chunk(b'data', declared=size)))
    struct.pack_into('<I', data, 4, len(data) - 8 + size)
    return bytes(data)


class WavHeaderTests(unittest.TestCase):
    def test_confirmed_44_byte_truncation_has_no_duration(self):
        raw = prefix_only()
        self.assertEqual(len(raw), 44)
        result = probe_wav_header(raw, len(raw), True)
        self.assertEqual(result['status'], 'malformed')
        self.assertIsNone(result['declared_duration_sec'])
        self.assertIsNone(result['duration_basis'])
        self.assertEqual(result['data_declared_bytes'], 16000)
        self.assertEqual(result['riff_declared_bytes'], 16044)
        self.assertEqual(result['provider_size_bytes'], 44)
        codes = {issue['code'] for issue in result['issues']}
        self.assertTrue({'provider_size_mismatch', 'truncated_chunk_payload'} <= codes)

    def test_unknown_tail_is_only_a_header_duration_declaration(self):
        result = probe_wav_header(prefix_only(), 16044)
        self.assertEqual(result['status'], 'observed')
        self.assertEqual(result['declared_duration_sec'], 1.0)
        self.assertEqual(result['duration_basis'], 'declared_data_bytes_divided_by_header_byte_rate')
        self.assertFalse(result['body_validated'])
        self.assertFalse(result['end_of_input'])
        self.assertEqual(result['coverage'], 'header_prefix_only')
        self.assertTrue(any(item['code'] == 'data_body_uninspected' for item in result['issues']))

    def test_complete_pcm_float_and_empty_data(self):
        for header, body, duration in ((fmt(), b'\0' * 16000, 1.0), (fmt(code=3, bits=32, extra=b'\0\0'), b'\0' * 32000, 1.0), (fmt(), b'', 0.0)):
            raw = riff(header, chunk(b'data', body))
            with self.subTest(duration=duration):
                result = probe_wav_header(raw, len(raw), True)
                self.assertEqual(result['status'], 'observed')
                self.assertEqual(result['declared_duration_sec'], duration)
                self.assertFalse(result['body_validated'])
                json.dumps(result, allow_nan=False)

    def test_provider_conflict_retains_both_sizes(self):
        result = probe_wav_header(prefix_only(), 99999)
        self.assertEqual(result['status'], 'size_mismatch')
        self.assertEqual(result['provider_size_bytes'], 99999)
        self.assertEqual(result['riff_declared_bytes'], 16044)
        self.assertIsNone(result['declared_duration_sec'])

    def test_duplicate_visible_chunks_and_data_order(self):
        for chunks in ((fmt(), chunk(b'data', b'\0\0'), fmt()),
                       (fmt(), chunk(b'data', b'\0\0'), chunk(b'data')),
                       (chunk(b'data'), fmt())):
            with self.subTest(chunks=chunks):
                result = probe_wav_header(riff(*chunks), end_of_input=True)
                self.assertEqual(result['status'], 'malformed')
                self.assertIsNone(result['declared_duration_sec'])

    def test_unsupported_profiles_preserve_raw_format(self):
        for header in (fmt(code=6), fmt(code=0xfffe), fmt(bits=40), fmt(code=3, bits=16), fmt(extra=b'\1\0')):
            result = probe_wav_header(riff(header, chunk(b'data')), end_of_input=True)
            self.assertEqual(result['status'], 'unsupported')
            self.assertIsNotNone(result['format_code'])
            self.assertIsNone(result['declared_duration_sec'])

    def test_zero_bad_rate_and_frame_alignment_reject(self):
        for header, body in ((fmt(rate=0), b''), (fmt(byte_rate=7), b''), (fmt(), b'abc')):
            result = probe_wav_header(riff(header, chunk(b'data', body)), end_of_input=True)
            self.assertEqual(result['status'], 'malformed')
            self.assertIsNone(result['declared_duration_sec'])

    def test_odd_padding_and_unsigned_extents(self):
        raw = riff(chunk(b'JUNK', b'x'), fmt(), chunk(b'data', b'\0\0'))
        self.assertEqual(probe_wav_header(raw, end_of_input=True)['status'], 'observed')
        raw = riff(fmt(), chunk(b'data', declared=0xffffffff))
        result = probe_wav_header(raw)
        self.assertEqual(result['status'], 'malformed')
        self.assertTrue(any(item['code'] == 'chunk_extent_outside_riff' for item in result['issues']))

    def test_exact_prefix_limit_and_larger_argument(self):
        raw = bytearray(riff(fmt(), chunk(b'JUNK', b'\0' * 65484), chunk(b'data', declared=16000)))
        self.assertEqual(len(raw), MAX_PREFIX_BYTES)
        struct.pack_into('<I', raw, 4, len(raw) - 8 + 16000)
        exact = probe_wav_header(bytes(raw), len(raw) + 16000)
        self.assertEqual(exact['status'], 'observed')
        bounded = probe_wav_header(bytes(raw) + b'X' * 1000, len(raw) + 16000, True)
        self.assertEqual(bounded['bytes_inspected'], MAX_PREFIX_BYTES)
        self.assertFalse(bounded['end_of_input'])
        self.assertEqual(bounded['declared_duration_sec'], 1.0)

    def test_strict_api_types(self):
        for raw in (None, '', bytearray(4), memoryview(b'1234'), 5):
            with self.subTest(raw=type(raw)), self.assertRaises(ValueError):
                probe_wav_header(raw)
        for size in (True, False, -1, 2**63, 1.0, '1'):
            with self.subTest(size=size), self.assertRaises(ValueError):
                probe_wav_header(b'', provider_size_bytes=size)
        for eof in (None, 1, 'true'):
            with self.subTest(eof=eof), self.assertRaises(ValueError):
                probe_wav_header(b'', end_of_input=eof)

    def test_arbitrary_prefixes_return_finite_serializable_observations(self):
        for raw in (b'', b'RIFF', bytes(11), b'RIFXabcdefgh', bytes(range(256)) * 256):
            for eof in (False, True):
                result = probe_wav_header(raw, end_of_input=eof)
                json.dumps(result, allow_nan=False)
                self.assertIsNone(result['declared_duration_sec'])
                self.assertFalse(result['body_validated'])
                self.assertLessEqual(result['bytes_inspected'], MAX_PREFIX_BYTES)

    def test_raw_bytes_unchanged_and_issues_do_not_grow_per_repeated_duplicate(self):
        raw = riff(fmt(), chunk(b'data'), *(fmt() for _ in range(100)))
        before = bytes(raw)
        result = probe_wav_header(raw, end_of_input=True)
        self.assertEqual(raw, before)
        self.assertEqual(sum(item['code'] == 'duplicate_fmt' for item in result['issues']), 1)
        self.assertLess(len(result['issues']), 10)
